version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: harmonyhub-postgres
    restart: always
    environment:
      POSTGRES_DB: harmonyhub
      POSTGRES_USER: harmony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: